version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"

    volumes:
      - ./:/usr/src/client
      - /usr/src/client/node_modules

